spring.application.name=FinTracker

spring.datasource.url=jdbc:mysql://localhost:3306/fintracker
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=your-256-bit-secret-key-must-be-at-least-32-chars-long
jwt.expiration=86400000

General.EXCEPTION_MESSAGE=Unexpected Error occured

UserService.EMAIL_EXISTS=This email already exists
UserService.USER_NOT_FOUND=User with given email is not found
UserService.INVALID_CREDENTIALS=Email or Password is invalid

AccountService.ACCOUNT_NAME_EXISTS=An account with this name already exists. Please choose a different name